# This is config file!

hub:
  world:
  x:
  y:
  z:
  yaw:
  pitch:
worlds:
  world:
    difficulty:
  world_nether:
    difficulty:
  world_the_end:
    difficulty:
  Survival:
    difficulty:
  Survival_nether:
    difficulty:
  Survival_end:
    difficulty:
  Shigen:
    difficulty:
  Shigen2:
    difficulty:
  PvP:
    difficulty: