name: CIVNCraft
description: You can do all!
author: CIVN
website: http://civn.xyz/
main: xyz.civn.civncraft.CIVNCraft
version: 1.0
commands:
   hub:
      description: hub command.
      aliases: [lobby, spawn]
      usage: /<command>
      permission: civncraft.hub
      permission-message: You don't have permission <permission>!
   sethub:
      description: sethub command.
      aliases: [setlobby, lobbyset, hubset]
      usage: /<command> {<X> <Y> <Z> <Yaw> <Pitch>}
      permission: civncraft.sethub
      permission-message: You don't have permission <permission>!
   hubloc:
      description: sethub command.
      aliases: [hublocation, hubl, lobbyloc]
      usage: /<command>
      permission: civncraft.hubloc
      permission-message: You don't have permission <permission>!
   seppuku:
      description: seppuku command.
      aliases: [die, death, sinu]
      usage: /<command>
      permission: civncraft.seppuku
      permission-message: You don't have permission <permission>!
   asiba:
      description: asiba command.
      aliases: [a, ashiba, footing]
      usage: /<command> <BlockID> <Amount> or /<command> to <BlockID>
      permission: civncraft.asiba
      permission-message: You don't have permission <permission>!
   civn:
      description: infomation command.
      aliases: civncraft
      usage: /<command>
      permission: civncraft.info
      permission-message: You don't have permission <permission>!
permissions:
   civncraft.*:
     description: All access CIVNCraft commands.
     children:
       civncraft.hub: true
       civncraft.sethub: true
       civncraft.hubloc: true
       civncraft.seppuku: true
       civncraft.asiba: true
       civncraft.info: true
   civncraft.hub:
     description: Hub command.
     default: true
   civncraft.sethub:
     description: Set hub command.
     default: op
   civncraft.hubloc:
     description: Show hub location command.
     default: op
   civncraft.seppuku:
     description: Seppuku command.
     default: true
   civncraft.asiba:
     description: Create asiba command.
     default: op
   civncraft.info:
     description: Show infomation command.
     default: true